import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { UserProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <NavBar />
          <main className="container mx-auto px-5 mt-4">{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
