import { BetProvider } from "@/context/BetContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { SportsTreeProvider } from "@/context/SportsTreeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <BetProvider>
      <SportsTreeProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </SportsTreeProvider>
    </BetProvider>
  );
}
